// The OpenNext handler is generated by `npm run build:cloudflare`.
// This small wrapper keeps the existing scheduled AutoPilot alongside Next routes.
// @ts-expect-error Generated during the Cloudflare build.
import { default as nextHandler } from './.open-next/worker.js';
import autoPilotWorker from './worker';

const autoPilot = autoPilotWorker as {
  scheduled?: (event: ScheduledEvent, env: unknown, ctx: ExecutionContext) => Promise<void>;
};

export default {
  fetch: nextHandler.fetch,
  async scheduled(event: ScheduledEvent, env: unknown, ctx: ExecutionContext) {
    await autoPilot.scheduled?.(event, env, ctx);
  },
};
