name = "animepulse"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "ANIMEPULSE_KV"
id = "f26230031c4c4c21902eae06428dd711"
