/**
 * Gemini AI Integration for AnimePulse
 * Generates anime articles using Google's Gemini AI
 */

const GEMINI_API_KEY = process.env.GEMINI_API_KEY || '';
const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent';

export interface GeneratedArticle {
  title: string;
  content: string;
  summary: string;
  tags: string[];
  readTime: number;
}

/**
 * Generate article using Gemini AI
 */
export async function generateArticle(
  newsItem: { title: string; description: string }
): Promise<GeneratedArticle> {
  const fallbackArticle: GeneratedArticle = {
    title: newsItem.title,
    content: `# ${newsItem.title}\n\n${newsItem.description}\n\n## Community Reaction\n\nThe anime community has been quick to react to this news. Fans on social media are expressing excitement and sharing their expectations. This update is certainly one of the highlights of the week in the industry.\n\n## Why It Matters\n\nDevelopments like this often signal new trends or major shifts in the anime landscape. Whether it's a new season announcement or a production update, it keeps the spirit of the medium alive and thriving.\n\nStay tuned to AnimePulse for more in-depth coverage and future updates on this story!\n\n*Content generated by AnimePulse Auto-Pilot Fallback System.*`,
    summary: newsItem.description,
    tags: ['anime', 'news', 'update'],
    readTime: 2,
  };

  if (!GEMINI_API_KEY) {
    console.warn('⚠️ No Gemini API key found, using fallback content');
    return fallbackArticle;
  }

  const prompt = `You are an expert anime journalist for AnimePulse. Write an engaging anime news article based on the following information:

Title: ${newsItem.title}
Description: ${newsItem.description}

Write a comprehensive article that includes:
1. An engaging introduction
2. Background information about the anime/series mentioned
3. Analysis of why this news is important
4. Fan reactions and community impact
5. What's coming next

Format the article in Markdown with proper headings. Make it fun and engaging for anime fans.

Also provide a 2-3 sentence summary at the end, separated by "---SUMMARY---"
And 3-5 relevant tags at the end, separated by "---TAGS---" (comma-separated)
`;

  try {
    const response = await fetch(`${GEMINI_API_URL}?key=${GEMINI_API_KEY}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt,
          }],
        }],
        generationConfig: {
          temperature: 0.7,
          maxOutputTokens: 2048,
        },
      }),
    });

    const data = await response.json();

    if (!response.ok || data.error) {
      console.error('Gemini API error:', data.error?.message || response.status);
      return fallbackArticle;
    }

    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text || '';

    // Parse the response
    const parts = generatedText.split('---SUMMARY---');
    const content = parts[0]?.trim() || '';
    const rest = parts[1]?.trim() || '';
    
    const summaryParts = rest.split('---TAGS---');
    const summary = summaryParts[0]?.trim() || newsItem.description;
    const tagsString = summaryParts[1]?.trim() || '';
    const tags = tagsString.split(',').map((t: string) => t.trim()).filter((t: string) => t);

    // Calculate read time (approx 200 words per minute)
    const wordCount = content.split(/\s+/).length;
    const readTime = Math.ceil(wordCount / 200);

    return {
      title: newsItem.title,
      content,
      summary,
      tags: tags.length > 0 ? tags : ['anime', 'news'],
      readTime,
    };
  } catch (error) {
    console.error('❌ Gemini generation failed:', error);
    return fallbackArticle;
  }
}

/**
 * Generate trending analysis
 */
export async function generateTrendingAnalysis(animeList: string[]): Promise<string> {
  if (!GEMINI_API_KEY) {
    return `Current trending anime include ${animeList.slice(0, 3).join(', ')}, and more. These shows are capturing fans' attention with their compelling stories and stunning animation.`;
  }

  const prompt = `As an anime expert, analyze why these anime are trending:
${animeList.join(', ')}

Write a short paragraph (3-4 sentences) explaining what makes these anime popular right now. Be engaging and informative.`;

  try {
    const response = await fetch(`${GEMINI_API_URL}?key=${GEMINI_API_KEY}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{ text: prompt }],
        }],
        generationConfig: {
          temperature: 0.7,
          maxOutputTokens: 500,
        },
      }),
    });

    const data = await response.json();
    return data.candidates?.[0]?.content?.parts?.[0]?.text || `These trending anime are gaining popularity for their compelling storytelling and animation quality.`;
  } catch (error) {
    console.error('Error generating trending analysis:', error);
    return `These trending anime are gaining popularity for their compelling storytelling and animation quality.`;
  }
}

/**
 * Generate review from rating and basic info
 */
export async function generateQuickReview(
  animeTitle: string,
  rating: number,
  genre: string
): Promise<string> {
  const prompt = `Write a short 2-3 sentence review for "${animeTitle}" (${genre}) rated ${rating}/10. Be concise and engaging.`;
  
  try {
    const response = await fetch(`${GEMINI_API_URL}?key=${GEMINI_API_KEY}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{ text: prompt }],
        }],
        generationConfig: {
          temperature: 0.7,
          maxOutputTokens: 200,
        },
      }),
    });

    const data = await response.json();
    return data.candidates?.[0]?.content?.parts?.[0]?.text || `${animeTitle} delivers an exceptional ${genre} experience worth watching.`;
  } catch {
    return `${animeTitle} delivers an exceptional ${genre} experience with stunning visuals and compelling storytelling.`;
  }
}
